spring:
  application:
    name: "Yansi-WMS-Spring"
  mvc:
    servlet:
      path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yansiwms
    username: root
    password: Pass.123
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.yansispring.entity
jwt:
  secret: "wsq520131425052026329"
  #分页插件
pagehelper:
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true